"""Typed containers returned by the core pipeline functions.

The dataclasses in this module make it easier to pass structured analysis state
between notebook-style script cells without leaking implementation details into
project-specific user scripts.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd


@dataclass(slots=True)
class ResultsPaths:
    """Collect all output locations for one input dataset."""

    source_path: Path
    results_dir: Path
    roi_mask_path: Path
    detailed_csv_path: Path
    excel_path: Path
    cell_mask_path: Path
    marker_mask_path: Path
    positive_cell_mask_path: Path
    optional_region_mask_path: Path


@dataclass(slots=True)
class LoadedImageChannels:
    """Store the loaded analysis channels and related metadata."""

    source_path: Path
    paths: ResultsPaths
    voxel_scale_zyx: tuple[float, float, float]
    cell_image: np.ndarray
    marker_image: np.ndarray
    optional_region_image: np.ndarray | None
    raw_shape_tzcyx: tuple[int, ...]
    raw_z_size: int
    is_3d: bool
    metadata: Any


@dataclass(slots=True)
class OptionalRegionSegmentationResult:
    """Hold the results of the optional third-channel segmentation."""

    mask: np.ndarray
    labels: np.ndarray
    threshold: float
    corrected_image: np.ndarray


@dataclass(slots=True)
class ColocalizationTables:
    """Bundle the detailed, per-cell, and per-ROI result tables."""

    detailed: pd.DataFrame
    summary: pd.DataFrame
    overview: pd.DataFrame


@dataclass(slots=True)
class ColocalizationRunResult:
    """Bundle label masks and tables generated by the Cellpose analysis."""

    cell_masks: np.ndarray
    marker_masks: np.ndarray
    positive_cell_masks: np.ndarray
    tables: ColocalizationTables
